# Generated by Django 4.0.4 on 2022-05-05 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('contact2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0.0)),
                ('nvis', models.IntegerField(default=0)),
                ('nrated', models.IntegerField(default=0)),
                ('company_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.vehicle')),
                ('model_name', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=100)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('displacement', models.FloatField(blank=True, null=True)),
                ('front_brake', models.CharField(choices=[('Disc', 'Disc'), ('Drum', 'Drum')], max_length=4)),
                ('back_brake', models.CharField(choices=[('Disc', 'Disc'), ('Drum', 'Drum')], max_length=4)),
                ('tank_capacity', models.FloatField(blank=True, null=True)),
                ('bhp', models.CharField(blank=True, max_length=50, null=True)),
                ('img_src', models.CharField(blank=True, max_length=150, null=True)),
            ],
            bases=('main.vehicle',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
            options={
                'unique_together': {('vehicle_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
            options={
                'unique_together': {('vehicle_id', 'user_id')},
            },
        ),
    ]
