# Generated by Django 4.0.4 on 2022-05-05 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.vehicle')),
                ('model_name', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=10)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('transmission', models.CharField(max_length=10)),
                ('displacement', models.IntegerField(blank=True, null=True)),
                ('gear_box', models.CharField(max_length=10)),
                ('seating_capacity', models.IntegerField(blank=True, null=True)),
                ('front_brake', models.CharField(default='Drum', max_length=10)),
                ('back_brake', models.CharField(default='Drum', max_length=10)),
                ('tank_capacity', models.FloatField(blank=True, null=True)),
                ('bhp', models.CharField(blank=True, max_length=50, null=True)),
                ('img_src', models.CharField(blank=True, max_length=150, null=True)),
            ],
            bases=('main.vehicle',),
        ),
    ]
