# Generated by Django 4.0.4 on 2022-05-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='back_brake',
            field=models.CharField(blank=True, default='Drum', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_brake',
            field=models.CharField(blank=True, default='Drum', max_length=10, null=True),
        ),
    ]
