# Generated by Django 4.0.4 on 2022-05-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_back_brake_alter_car_front_brake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear_box',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
