# Generated by Django 4.0.4 on 2022-05-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.vehicle')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('num_tyre', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(max_length=10)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('transmission', models.CharField(max_length=10)),
                ('displacement', models.IntegerField(blank=True, null=True)),
                ('payload', models.FloatField(blank=True, null=True)),
                ('tank_capacity', models.FloatField(blank=True, null=True)),
                ('bhp', models.CharField(blank=True, max_length=50, null=True)),
                ('img_src', models.CharField(blank=True, max_length=150, null=True)),
            ],
            bases=('main.vehicle',),
        ),
    ]
